from __future__ import annotations

from copy import deepcopy
from datetime import datetime, timedelta, timezone


NOW = datetime.now(timezone.utc)

DEMO_ALERTS: list[dict] = [
    {
        "id": "ALT-2026-00841",
        "transaction_id": "TXN-882104",
        "company_id": "CMP-0142",
        "company_name": "Meridian Global Trading Ltd",
        "alert_type": "Sanctions & rapid movement",
        "status": "Open",
        "description": "High-value transfer involving a newly disclosed owner and a high-risk destination.",
        "amount": 4_850_000,
        "currency": "USD",
        "origin_country": "Singapore",
        "destination_country": "United Arab Emirates",
        "created_at": NOW - timedelta(minutes=34),
        "transaction": {
            "counterparty": "Al Noor Commodities FZE",
            "occurred_at": NOW - timedelta(minutes=51),
            "channel": "SWIFT",
            "purpose": "Trade settlement",
        },
        "company": {
            "industry": "Commodities Trading",
            "country": "Singapore",
            "risk_rating": "High",
            "pep": True,
            "sanctions_match": True,
            "beneficial_owner_layers": 5,
            "prior_cases": 3,
            "baseline_average_amount": 620_000,
            "baseline_monthly_frequency": 4,
        },
        "signals": {
            "rapid_transfers": 4,
            "amount_ratio": 7.82,
            "fatf_risk": "High",
            "supervisory_attention": True,
            "new_corridor": True,
            # Low-confidence key driver: fuzzy sanctions match + stale ownership data
            "sanctions_match_type": "fuzzy",
            "sanctions_similarity": 82,
            "ownership_freshness_days": 335,
            "baseline_freshness_days": 40,
            "country_data_freshness_days": 45,
            "cases_freshness_days": 70,
        },
    },
    {
        "id": "ALT-2026-00839",
        "transaction_id": "TXN-882077",
        "company_id": "CMP-0317",
        "company_name": "NordWerk Industrial GmbH",
        "alert_type": "Structuring pattern",
        "status": "In review",
        "description": "Three transfers were executed just below an internal review threshold.",
        "amount": 987_500,
        "currency": "EUR",
        "origin_country": "Germany",
        "destination_country": "Türkiye",
        "created_at": NOW - timedelta(hours=2),
        "transaction": {
            "counterparty": "Bosphorus Machinery AS",
            "occurred_at": NOW - timedelta(hours=3),
            "channel": "SEPA",
            "purpose": "Equipment purchase",
        },
        "company": {
            "industry": "Industrial Manufacturing",
            "country": "Germany",
            "risk_rating": "Medium",
            "pep": False,
            "sanctions_match": False,
            "beneficial_owner_layers": 2,
            "prior_cases": 1,
            "baseline_average_amount": 410_000,
            "baseline_monthly_frequency": 8,
        },
        "signals": {
            "rapid_transfers": 3,
            "amount_ratio": 2.41,
            "fatf_risk": "Medium",
            "supervisory_attention": True,
            "new_corridor": False,
            # Medium confidence: slightly stale baseline for behavioural/transaction factors
            "sanctions_match_type": "none",
            "ownership_freshness_days": 55,
            "baseline_freshness_days": 210,
            "country_data_freshness_days": 80,
            "cases_freshness_days": 95,
        },
    },
    {
        "id": "ALT-2026-00836",
        "transaction_id": "TXN-882012",
        "company_id": "CMP-0208",
        "company_name": "Pacific Horizon Capital",
        "alert_type": "Behavioural deviation",
        "status": "Open",
        "description": "Transaction amount and destination differ materially from the client's baseline.",
        "amount": 2_300_000,
        "currency": "USD",
        "origin_country": "Singapore",
        "destination_country": "Vietnam",
        "created_at": NOW - timedelta(hours=4),
        "transaction": {
            "counterparty": "Viet Delta Holdings JSC",
            "occurred_at": NOW - timedelta(hours=5),
            "channel": "SWIFT",
            "purpose": "Capital investment",
        },
        "company": {
            "industry": "Investment Management",
            "country": "Singapore",
            "risk_rating": "Medium",
            "pep": False,
            "sanctions_match": False,
            "beneficial_owner_layers": 3,
            "prior_cases": 1,
            "baseline_average_amount": 515_000,
            "baseline_monthly_frequency": 5,
        },
        "signals": {
            "rapid_transfers": 1,
            "amount_ratio": 4.47,
            "fatf_risk": "Medium",
            "supervisory_attention": True,
            "new_corridor": True,
            "sanctions_match_type": "none",
            "ownership_freshness_days": 40,
            "baseline_freshness_days": 30,
            "country_data_freshness_days": 50,
            "cases_freshness_days": 60,
        },
    },
    {
        "id": "ALT-2026-00831",
        "transaction_id": "TXN-881941",
        "company_id": "CMP-0094",
        "company_name": "Atlas Renewable Energy BV",
        "alert_type": "High-value threshold",
        "status": "Open",
        "description": "A high-value transfer exceeded the monitoring threshold.",
        "amount": 1_250_000,
        "currency": "EUR",
        "origin_country": "Netherlands",
        "destination_country": "Canada",
        "created_at": NOW - timedelta(hours=7),
        "transaction": {
            "counterparty": "Northern Grid Partners Inc",
            "occurred_at": NOW - timedelta(hours=8),
            "channel": "SWIFT",
            "purpose": "Project financing",
        },
        "company": {
            "industry": "Renewable Energy",
            "country": "Netherlands",
            "risk_rating": "Low",
            "pep": False,
            "sanctions_match": False,
            "beneficial_owner_layers": 1,
            "prior_cases": 0,
            "baseline_average_amount": 980_000,
            "baseline_monthly_frequency": 6,
        },
        "signals": {
            "rapid_transfers": 0,
            "amount_ratio": 1.28,
            "fatf_risk": "Low",
            "supervisory_attention": True,
            "new_corridor": False,
            # High confidence: fresh, complete, corroborated inputs
            "sanctions_match_type": "none",
            "ownership_freshness_days": 20,
            "baseline_freshness_days": 25,
            "country_data_freshness_days": 15,
            "cases_freshness_days": 30,
        },
    },
    {
        "id": "ALT-2026-00828",
        "transaction_id": "TXN-881903",
        "company_id": "CMP-0441",
        "company_name": "Seoul Digital Networks Co",
        "alert_type": "Round-number transfer",
        "status": "In review",
        "description": "Round-number transfer raised an informational monitoring alert.",
        "amount": 500_000,
        "currency": "USD",
        "origin_country": "South Korea",
        "destination_country": "Japan",
        "created_at": NOW - timedelta(hours=10),
        "transaction": {
            "counterparty": "Nippon Cloud Systems KK",
            "occurred_at": NOW - timedelta(hours=11),
            "channel": "SWIFT",
            "purpose": "Software licence",
        },
        "company": {
            "industry": "Technology",
            "country": "South Korea",
            "risk_rating": "Low",
            "pep": False,
            "sanctions_match": False,
            "beneficial_owner_layers": 1,
            "prior_cases": 0,
            "baseline_average_amount": 460_000,
            "baseline_monthly_frequency": 12,
        },
        "signals": {
            "rapid_transfers": 0,
            "amount_ratio": 1.09,
            "fatf_risk": "Low",
            "supervisory_attention": False,
            "new_corridor": False,
            "sanctions_match_type": "none",
            "ownership_freshness_days": 45,
            "baseline_freshness_days": 50,
            "country_data_freshness_days": 40,
            "cases_freshness_days": 55,
        },
    },
    {
        "id": "ALT-2026-00822",
        "transaction_id": "TXN-881824",
        "company_id": "CMP-0116",
        "company_name": "Maple Institutional Trust",
        "alert_type": "Velocity threshold",
        "status": "Open",
        "description": "Transfer frequency increased above the client's monthly baseline.",
        "amount": 780_000,
        "currency": "CAD",
        "origin_country": "Canada",
        "destination_country": "United Kingdom",
        "created_at": NOW - timedelta(hours=14),
        "transaction": {
            "counterparty": "Thames Custody Services plc",
            "occurred_at": NOW - timedelta(hours=15),
            "channel": "SWIFT",
            "purpose": "Custody settlement",
        },
        "company": {
            "industry": "Institutional Investment",
            "country": "Canada",
            "risk_rating": "Low",
            "pep": False,
            "sanctions_match": False,
            "beneficial_owner_layers": 1,
            "prior_cases": 0,
            "baseline_average_amount": 730_000,
            "baseline_monthly_frequency": 18,
        },
        "signals": {
            "rapid_transfers": 2,
            "amount_ratio": 1.07,
            "fatf_risk": "Low",
            "supervisory_attention": False,
            "new_corridor": False,
            "sanctions_match_type": "none",
            "ownership_freshness_days": 35,
            "baseline_freshness_days": 28,
            "country_data_freshness_days": 22,
            "cases_freshness_days": 40,
        },
    },
]


def get_demo_alerts() -> list[dict]:
    return deepcopy(DEMO_ALERTS)
